# Generated by Django 4.1 on 2022-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('مجتبا', 'مجتبا'), ('امیر', 'امیر'), ('بابا', 'بابا')], max_length=30)),
                ('title', models.CharField(max_length=256)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cost_type', models.CharField(choices=[('هزینه های جاری', 'هزینه های جاری'), ('خوراک', 'خوراک')], max_length=30)),
                ('date', models.DateField()),
                ('info', models.TextField()),
            ],
        ),
    ]
