# Generated by Django 4.1 on 2022-08-08 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('mojtaba', 'mojtaba'), ('amir', 'amir'), ('baba', 'baba')], max_length=30)),
                ('title', models.CharField(max_length=256)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('cost_type', models.CharField(choices=[('1', 'هزینه های جاری'), ('2', 'خوراک')], max_length=30)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=11)),
                ('time_enterd', models.DateTimeField()),
                ('time_exited', models.DateTimeField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('info', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذی'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], max_length=30)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.workermodel')),
            ],
        ),
    ]
