# Generated by Django 4.0.6 on 2022-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsmodel',
            name='cost_type',
            field=models.CharField(choices=[('هزینه های جاری', 'هزینه های جاری'), ('خوراک', 'خوراک')], max_length=30),
        ),
        migrations.AlterField(
            model_name='costsmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costsmodel',
            name='who',
            field=models.CharField(choices=[('مجتبا', 'مجتبا'), ('امیر', 'امیر'), ('بابا', 'بابا')], max_length=30),
        ),
    ]
