# Generated by Django 4.1 on 2022-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_costsmodel_cost_type_alter_costsmodel_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seller', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=500)),
                ('acheteur', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
